.TH GIT_MANAGER 1 git_manager\-VERSION
.SH NAME
git_manager \- git repository manager
.SH SYNOPSIS
.B git_manager
.RB [ \-v ]
.SH DESCRIPTION
git_manager is a script for managing multiple git repositories and branches
.P
git_manager has options for findiding and updating multiple repos
.SH OPTIONS
.TP
.B \-F
SEARCH FOR GIT REPOS.
Searches home directory for git repos
(This must completed at least once to update the cache used by other functions)
.TP
.B \-a
BRANCH AUTO.
Automatically approves per branch confirmation prompts (To avoid pressing 'y' a bunch of times). Can be combined with -A
.TP
.B \-A
REPO AUTO.
Automatically approves per repo confirmation prompts (To avoid pressing 'y' a bunch of times). Can be combined with -a
.TP
.B \-f
FETCH REPOS.
Fetch and prune all repos
.TP
.B \-s
CHECK FOR CHANGES.
Checks each repository for changes which have not been comitted and provides a simple summary
.TP
.B \-S
LIST CHANGES.
List all changes in each repository which have not been comitted
.TP
.B \-p
PULL.
Prompts you to pull each branch in your git repositories
.TP
.B \-P
PULL AND PUSH.
Prompts you to pull+push each branch in your git repositories
.TP
.B \-c
ADD ALL CHANGES + COMMIT + PUSH.
Prompts you to add all changes + commit + push each git repository
.TP
.B \-C
ADD ALL CHANGES + COMMIT + PUSH NO DIFF.
Prompts you to add all changes + commit + push each git repository but will not prompt to show diff
.TP
.B \-m
MERGE ORIGIN/MASTER INTO BRANCHES.
Prompts you to merge origin/master into each branch in your git repositories
.TP
.B \-M
AUTOMERGE ORIGIN/MASTER INTO BRANCHES.
Attempts to automatically merge origin/master into each branch in your git repositories
.TP
.B \-r
REBASE BRANCHES.
Prompts you to rebase each branch on origin/master for each repo in your git repositories
.TP
.B \-R
AUTOREBASE BRANCHES.
Attempts to rebase each branch on origin/master for each repo in your git repositories
.TP
.B \-e
EVERYTHING.
Prompts you to add, commit, pull, push all branches of all repos
.TP
.B \-E
EVERYTHING AUTO.
Attempts to automatically add, commit, pull, push all branches of all repos
.TP
.B \-b clean
CLEAN OLD BRANCHES.
Prompts you to delete any branches in your git repositories which are 0 commits ahead of origin/master
.TP
.B \-b master
COMPARE MASTER.
Compares each branch in your git repositories against origin/master
.TP
.B \-B master
COMPARE MASTER NO FETCH.
Compares each branch in your git repositories against origin/master
.TP
.B \-b remote
COMPARE REMOTE.
Compares each branch in your git repositories against it's remote branch
.TP
.B \-B remote
COMPARE REMOTE NO FETCH.
Compares each branch in your git repositories against it's remote branch
.TP
.B \-\-sync
PUSH AND PULL ALL BRANCHES OF ALL REPOSITORIES.
.TP
.B \-h --help
HELP.
Displays this message
.SH USAGE
provide no args for interactive mode.
.SH SEE ALSO
.BR git (1)
