.TH GIT_MANAGER 1 git_manager\-VERSION
.SH NAME
git_manager \- git repository manager
.SH SYNOPSIS
.B git_manager
.RB [ \-v ]
.SH DESCRIPTION
git_manager is a script for managing multiple git repositories and branches
.P
git_manager has options for findiding and updating multiple repos
.SH OPTIONS
.TP
.B \-s
prints summary of known repos
.SH USAGE
provide no args for interactive mode.
.SH SEE ALSO
.BR git (1)
